### ISSUE TITLE
update sqwidget default jquery version

### ISSUE THREAD

**Issue by csolar** [premasagar/sqwidget#68]
if jquery is not present in the host page sqwidget should load the latest jquery  version. At the moment it loads 1.6. 1 which is a bit old. The latest version at the time of writing is 1.8.2 so we could change the current configuration parameter that currently reads:
http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js

to
http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js

or we could use the following link which always refers to the latest version:
http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js

**Comment by premasagar** [comment]
We should use the specific 1.8.2 version (and keep Sqwidget updated, in tandem with new versions of jQuery), because the specific versions have far-future browser caching, where as the latest version file does not.

Also, instead of using 'http://', we should use '//'. So instead of 'http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js' we should use '//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js'. This will mean that the https version of jQuery will load if Sqwidget is on an https host page.
