### ISSUE TITLE
Adding missing type attribute on widget.config container fixes failure in IE7

### ISSUE THREAD

**Issue by maskingtape** [premasagar/sqwidget#72]
TEST:
within a sqwidget widget as html page

```
<script>
  widget.config({
    "name": "matchstats",
    "version": "0.1.0",
    "basePath": "{{ site.widgetBaseUrl }}",
    "pluginPath": "{{ site.pluginBaseUrl }}",
    "dependencies": (widget.getSetting('test')) ? ['pa-widgets-core', 'mocha-chai-tester'] : ['pa-widgets-core']
  });
</script>
```

Fails in IE7 (i.e. does not load plugins)

This

```
<script type="text/javascript">
  widget.config({
    "name": "matchstats",
    "version": "0.1.0",
    "basePath": "{{ site.widgetBaseUrl }}",
    "pluginPath": "{{ site.pluginBaseUrl }}",
    "dependencies": (widget.getSetting('test')) ? ['pa-widgets-core', 'mocha-chai-tester'] : ['pa-widgets-core']
  });
</script>
```

Does load the plugins.

**Comment by premasagar** [comment]
Probably due to Sqwidget attempting to select scripts on [line 1315](https://github.com/premasagar/sqwidget/blob/d24262fae3e4d9707b67ba1b56a256b582d0a207/sqwidget.js#L1315):

```
j.filter("script:not([type]), script[type='text/javascript'], script[type='application/javascript']")
```

It could be the `:not` filter failing IE7 or it could be the `:not` in combination with the `[type]` attribute selector. A report of IE7 flakiness with attribute selectors: http://www.impressivewebs.com/buggy-css-selectors-cross-browser-jquery/
